from typing import List, Dict, Any
from app.models.passage import PassageModel

class VectorSearchRepository:
    """
    Handles native MongoDB Atlas $vectorSearch operations.
    Executes specialized hardware-accelerated vector pipelines directly against 
     the database engine to retrieve semantically similar passages.
    """
    
    @staticmethod
    async def find_semantic_candidates(
        query_embedding: List[float],
        project_id: str,
        exclude_document_id: str,
        limit: int = 15,
        min_score: float = 0.65
    ) -> List[Dict[str, Any]]:
        """
        Queries the Atlas vector index for passages matching the semantic meaning 
        of the query embedding. Strictly isolates the search to the active project 
        and prevents a document from matching against itself.
        """
        
        # Construct the exact filter for the Atlas Search nodes
        # This requires the fields to be explicitly mapped as "filter" types in the index
        search_filter = {
            "$and": [
                {"project_id": {"$eq": project_id}},
                {"document_id": {"$ne": exclude_document_id}}
            ]
        }
        
        pipeline = [
            {
                "$vectorSearch": {
                    "index": "passage_semantic_index",
                    "path": "embedding",
                    "queryVector": query_embedding,
                    # numCandidates determines the scope of the exact nearest neighbor 
                    # graph traversal. A higher multiple of 'limit' increases recall accuracy.
                    "numCandidates": limit * 10,
                    "limit": limit,
                    "filter": search_filter
                }
            },
            {
                # Project only the necessary fields to minimize network payload
                "$project": {
                    "_id": 0,
                    "passage_id": {"$toString": "$_id"},
                    "document_id": 1,
                    "passage_index": 1,
                    "text": 1,
                    "char_span": 1,
                    # Extract the native cosine similarity score generated by the DB
                    "similarity_score": {"$meta": "vectorSearchScore"}
                }
            },
            {
                # Filter out low-confidence matches at the database level before transmission
                "$match": {
                    "similarity_score": {"$gte": min_score}
                }
            }
        ]

        # Execute the raw pipeline through Beanie's motor collection
        candidates = await PassageModel.aggregate(pipeline).to_list()
        
        return candidates